/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/comparsion_test.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include "../utilits/s21_utility.h"
#include "../s21_decimal.h"

START_TEST(is_equal_simple)
{
s21_decimal decimal;
s21_decimal second_decimal;
init_decimal(&decimal);
init_decimal(&second_decimal);
int A = 5123;
convertation_result status = s21_from_int_to_decimal(A, &decimal);
convertation_result second_status = s21_from_int_to_decimal(A, &second_decimal);
ck_assert_int_eq(1, s21_is_equal(decimal, second_decimal));

}
END_TEST

START_TEST(is_equal_0_decimal)
{
s21_decimal decimal;
s21_decimal second_decimal;
init_decimal(&decimal);
init_decimal(&second_decimal);
int A = 5123;
convertation_result status = s21_from_int_to_decimal(A, &decimal);
ck_assert_int_eq(0, s21_is_equal(decimal, second_decimal));

}
END_TEST

START_TEST(is_not_equal)
{
s21_decimal decimal;
s21_decimal second_decimal;
init_decimal(&decimal);
init_decimal(&second_decimal);
int A = 5123;
int B = 5122;
convertation_result status = s21_from_int_to_decimal(A, &decimal);
convertation_result second_status = s21_from_int_to_decimal(B, &second_decimal);
ck_assert_int_eq(1, s21_is_not_equal(decimal, second_decimal));

}
END_TEST

START_TEST(is_not_equal_SIGN)
{
s21_decimal decimal;
s21_decimal second_decimal;
init_decimal(&decimal);
init_decimal(&second_decimal);
int A = -5123;
int B = 5123;
convertation_result status = s21_from_int_to_decimal(A, &decimal);
convertation_result second_status = s21_from_int_to_decimal(B, &second_decimal);
ck_assert_int_eq(1, s21_is_not_equal(decimal, second_decimal));

}
END_TEST

START_TEST(is_greater_stand)
{
s21_decimal decimal;
s21_decimal second_decimal;
init_decimal(&decimal);
init_decimal(&second_decimal);
int A = -5123;
int B = 5123;
convertation_result status = s21_from_int_to_decimal(A, &decimal);
convertation_result second_status = s21_from_int_to_decimal(B, &second_decimal);
ck_assert_int_eq(1, s21_is_greater(second_decimal, decimal));

}
END_TEST

START_TEST(is_greater_0)
{
s21_decimal decimal;
s21_decimal second_decimal;
init_decimal(&decimal);
init_decimal(&second_decimal);
int A = 0;
int B = 5123;
convertation_result status = s21_from_int_to_decimal(A, &decimal);
convertation_result second_status = s21_from_int_to_decimal(B, &second_decimal);
ck_assert_int_eq(0, s21_is_greater(decimal, second_decimal));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, is_equal_simple);
    tcase_add_test(tc1_1, is_equal_0_decimal);
    tcase_add_test(tc1_1, is_not_equal);
    tcase_add_test(tc1_1, is_not_equal_SIGN);
    tcase_add_test(tc1_1, is_greater_stand);
    tcase_add_test(tc1_1, is_greater_0);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
